### ISSUE TITLE
ASAN memory leaks

### ISSUE THREAD

**Issue by jeroenooms** [hadley/xml2#102]
ASAN says we are leaking memory. One place I narrowed down is in `xml_attr`:

```r
doc <- xml2::read_html('<a href="http://www.google.com" />')
nodes <- xml2::xml_find_all(doc, "//a[@href]")
links <- xml2::xml_attr(nodes, "href")
```

Gives:

```
> doc <- xml2::read_html('<a href="http://www.google.com" />')
> nodes <- xml2::xml_find_all(doc, "//a[@href]")
> links <- xml2::xml_attr(nodes, "href")
>
> q('no')

=================================================================
==22520==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 22 byte(s) in 1 object(s) allocated from:
    #0 0x7f678ff0bf4a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x93f4a)
    #1 0x7f678293c7f8 in xmlStrndup__internal_alias /root/libxml2-2.9.4/xmlstring.c:45

SUMMARY: AddressSanitizer: 22 byte(s) leaked in 1 allocation(s).
```

The docs for `xmlGetProp` and `xmlGetNoNsProp` state *It's up to the caller to free the memory with xmlFree()*. Are we doing that somewhere?
 
There are others too, here is what leaks during the unit tests:

```
DONE ===========================================================================
> q("no")
=================================================================
==22774==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 46 byte(s) in 10 object(s) allocated from:
    #0 0x7f783dd43f4a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x93f4a)
    #1 0x7f782f7567f8 in xmlStrndup__internal_alias /root/libxml2-2.9.4/xmlstring.c:45

Direct leak of 17 byte(s) in 2 object(s) allocated from:
    #0 0x7f783dd43f4a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x93f4a)
    #1 0x7f782f713014 in xmlURIUnescapeString__internal_alias /root/libxml2-2.9.4/uri.c:1622

Indirect leak of 480 byte(s) in 4 object(s) allocated from:
    #0 0x7f783dd43f4a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x93f4a)
    #1 0x7f782f7065e5 in xmlStaticCopyNode /root/libxml2-2.9.4/tree.c:4201

Indirect leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f783dd43f4a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x93f4a)
    #1 0x7f782f701702 in xmlNewNodeEatName__internal_alias /root/libxml2-2.9.4/tree.c:2271

Indirect leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f783dd43f4a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x93f4a)
    #1 0x7f782f7a87dd in xmlSAX2TextNode /root/libxml2-2.9.4/SAX2.c:1856

Indirect leak of 16 byte(s) in 4 object(s) allocated from:
    #0 0x7f783dd43f4a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x93f4a)
    #1 0x7f782f7567f8 in xmlStrndup__internal_alias /root/libxml2-2.9.4/xmlstring.c:45

SUMMARY: AddressSanitizer: 799 byte(s) leaked in 22 allocation(s).
```

**Comment by jimhester** [comment]
For my own reference I needed to increase the docker machine memory from 1024 to get the BH dependency to build.

**Comment by jeroenooms** [comment]
I added a dockerfile to the repo to have this automatically checked on dockerhub. But hadley hasn't enabled it yet.

Here is example output from my own repo: https://hub.docker.com/r/jeroenooms/xml2/builds/b7zpkqpwc6mrqjah9nbbjlh/
